"""auto_migration_20260308_1803

Revision ID: a3a2a33b9032
Revises: 3eb7062a735d
Create Date: 2026-03-08 18:03:20.146463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a2a33b9032'
down_revision: Union[str, None] = '3eb7062a735d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
