"""add_receptions_work_types

Revision ID: 3eb7062a735d
Revises: 8ac76f038097
Create Date: 2026-03-08 18:02:23.495825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eb7062a735d'
down_revision: Union[str, None] = '8ac76f038097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_types_name'), 'work_types', ['name'], unique=True)
    op.create_table('receptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('work_type_id', sa.UUID(), nullable=True),
    sa.Column('reported_problem', sa.Text(), nullable=True),
    sa.Column('entry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.String(length=100), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('fuel_level', sa.String(length=20), nullable=True),
    sa.Column('vin_number', sa.String(length=50), nullable=True),
    sa.Column('current_status', sa.Enum('NEW', 'IN_PROGRESS', 'PAUSED', 'FINISHED', 'WARRANTY_REVISION', name='reception_status'), server_default='NEW', nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='fk_receptions_customer_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='fk_receptions_vehicle_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name='fk_receptions_work_type_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receptions_current_status'), 'receptions', ['current_status'], unique=False)
    op.create_index('ix_receptions_current_status_entry_at', 'receptions', ['current_status', 'entry_at'], unique=False)
    op.create_index(op.f('ix_receptions_customer_id'), 'receptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_receptions_entry_at'), 'receptions', ['entry_at'], unique=False)
    op.create_index(op.f('ix_receptions_vehicle_id'), 'receptions', ['vehicle_id'], unique=False)
    op.create_index('ix_receptions_vehicle_id_entry_at', 'receptions', ['vehicle_id', 'entry_at'], unique=False)
    op.create_index(op.f('ix_receptions_vin_number'), 'receptions', ['vin_number'], unique=False)
    op.create_index(op.f('ix_receptions_work_type_id'), 'receptions', ['work_type_id'], unique=False)
    op.add_column('customers', sa.Column('identification', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_customers_identification'), 'customers', ['identification'], unique=True)
    op.add_column('vehicles', sa.Column('vin_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_vehicles_vin_number'), 'vehicles', ['vin_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vin_number'), table_name='vehicles')
    op.drop_column('vehicles', 'vin_number')
    op.drop_index(op.f('ix_customers_identification'), table_name='customers')
    op.drop_column('customers', 'identification')
    op.drop_index(op.f('ix_receptions_work_type_id'), table_name='receptions')
    op.drop_index(op.f('ix_receptions_vin_number'), table_name='receptions')
    op.drop_index('ix_receptions_vehicle_id_entry_at', table_name='receptions')
    op.drop_index(op.f('ix_receptions_vehicle_id'), table_name='receptions')
    op.drop_index(op.f('ix_receptions_entry_at'), table_name='receptions')
    op.drop_index(op.f('ix_receptions_customer_id'), table_name='receptions')
    op.drop_index('ix_receptions_current_status_entry_at', table_name='receptions')
    op.drop_index(op.f('ix_receptions_current_status'), table_name='receptions')
    op.drop_table('receptions')
    op.drop_index(op.f('ix_work_types_name'), table_name='work_types')
    op.drop_table('work_types')
    # ### end Alembic commands ###
