"""add_reception_details

Revision ID: 297e537f9198
Revises: a3a2a33b9032
Create Date: 2026-03-08 18:20:48.737487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297e537f9198'
down_revision: Union[str, None] = 'a3a2a33b9032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reception_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reception_id', sa.UUID(), nullable=False),
    sa.Column('work_type_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('work_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reception_id'], ['receptions.id'], name='fk_reception_details_reception_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name='fk_reception_details_work_type_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reception_details_reception_id', 'reception_details', ['reception_id'], unique=False)
    op.create_index('ix_reception_details_work_type_id', 'reception_details', ['work_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reception_details_work_type_id', table_name='reception_details')
    op.drop_index('ix_reception_details_reception_id', table_name='reception_details')
    op.drop_table('reception_details')
    # ### end Alembic commands ###
