"""auto_migration_20260308_1526

Revision ID: 08463a256b60
Revises: 7ac0fa36090a
Create Date: 2026-03-08 15:26:12.580967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08463a256b60'
down_revision: Union[str, None] = '7ac0fa36090a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=True)
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.add_column('work_order_items', sa.Column('currency_id', sa.UUID(), nullable=True))
    op.alter_column('work_order_items', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('work_order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_work_order_items_currency_id'), 'work_order_items', ['currency_id'], unique=False)
    op.create_foreign_key(None, 'work_order_items', 'currencies', ['currency_id'], ['id'], ondelete='SET NULL')
    op.alter_column('work_orders', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('work_orders', 'status',
               existing_type=postgresql.ENUM('received', 'in_progress', 'delivered', name='order_status'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_orders', 'status',
               existing_type=postgresql.ENUM('received', 'in_progress', 'delivered', name='order_status'),
               server_default=sa.text("'received'::order_status"),
               existing_nullable=False)
    op.alter_column('work_orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_constraint(None, 'work_order_items', type_='foreignkey')
    op.drop_index(op.f('ix_work_order_items_currency_id'), table_name='work_order_items')
    op.alter_column('work_order_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('work_order_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_column('work_order_items', 'currency_id')
    op.alter_column('vehicles', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v4()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
