"""auto_migration_20260308_1915

Revision ID: 80249f83148f
Revises: 5d8ce4790a41
Create Date: 2026-03-08 19:15:24.915976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80249f83148f'
down_revision: Union[str, None] = '5d8ce4790a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
