"""add_discount_percentage_to_work_order_lines

Revision ID: 5d8ce4790a41
Revises: 35310d98cb8b
Create Date: 2026-03-08 19:14:13.653899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8ce4790a41'
down_revision: Union[str, None] = '35310d98cb8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_order_lines', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_order_lines', 'discount_percentage')
    # ### end Alembic commands ###
